DROP DATABASE IF EXISTS ecom_db;
CREATE DATABASE ecom_db;
USE ecom_db;

CREATE TABLE Categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 10, 
  category_id INT,
  FOREIGN KEY (category_id) 
    REFERENCES Categories(id)
    ON DELETE SET NULL  
);

CREATE TABLE Tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(255) NOT NULL
);

CREATE TABLE ProductTags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  tag_id INT NOT NULL,
  FOREIGN KEY (product_id) 
    REFERENCES Products(id)
    ON DELETE CASCADE,
  FOREIGN KEY (tag_id)
    REFERENCES Tags(id)
    ON DELETE CASCADE  
);
